using System.Text.Json.Serialization;
using Square.Core;

namespace Square.Merchants;

public record ListMerchantsRequest
{
    /// <summary>
    /// The cursor generated by the previous response.
    /// </summary>
    [JsonIgnore]
    public int? Cursor { get; set; }

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
