using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class CatalogImage 
    {
        public CatalogImage(string name = null,
            string url = null,
            string caption = null)
        {
            Name = name;
            Url = url;
            Caption = caption;
        }

        /// <summary>
        /// The internal name of this image. Identifies this image in calls to the
        /// Connect APIs.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; }

        /// <summary>
        /// The URL of this image. Generated by Square after an image is uploaded
        /// to the CreateCatalogImage endpoint.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; }

        /// <summary>
        /// A caption that describes what is shown in the image. Displayed in the
        /// Square Online Store.
        /// </summary>
        [JsonProperty("caption")]
        public string Caption { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder()
                .Name(Name)
                .Url(Url)
                .Caption(Caption);
            return builder;
        }

        public class Builder
        {
            private string name;
            private string url;
            private string caption;

            public Builder() { }
            public Builder Name(string value)
            {
                name = value;
                return this;
            }

            public Builder Url(string value)
            {
                url = value;
                return this;
            }

            public Builder Caption(string value)
            {
                caption = value;
                return this;
            }

            public CatalogImage Build()
            {
                return new CatalogImage(name,
                    url,
                    caption);
            }
        }
    }
}