using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square.Http.Client;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class CreateCustomerCardResponse 
    {
        public CreateCustomerCardResponse(IList<Models.Error> errors = null,
            Models.Card card = null)
        {
            Errors = errors;
            Card = card;
        }

        [JsonIgnore]
        public HttpContext Context { get; internal set; }

        /// <summary>
        /// Any errors that occurred during the request.
        /// </summary>
        [JsonProperty("errors")]
        public IList<Models.Error> Errors { get; }

        /// <summary>
        /// Represents the payment details of a card to be used for payments. These
        /// details are determined by the `card_nonce` generated by `SqPaymentForm`.
        /// </summary>
        [JsonProperty("card")]
        public Models.Card Card { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder()
                .Errors(Errors)
                .Card(Card);
            return builder;
        }

        public class Builder
        {
            private IList<Models.Error> errors = new List<Models.Error>();
            private Models.Card card;

            public Builder() { }
            public Builder Errors(IList<Models.Error> value)
            {
                errors = value;
                return this;
            }

            public Builder Card(Models.Card value)
            {
                card = value;
                return this;
            }

            public CreateCustomerCardResponse Build()
            {
                return new CreateCustomerCardResponse(errors,
                    card);
            }
        }
    }
}