using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class CreateCustomerCardRequest 
    {
        public CreateCustomerCardRequest(string cardNonce,
            Models.Address billingAddress = null,
            string cardholderName = null,
            string verificationToken = null)
        {
            CardNonce = cardNonce;
            BillingAddress = billingAddress;
            CardholderName = cardholderName;
            VerificationToken = verificationToken;
        }

        /// <summary>
        /// A card nonce representing the credit card to link to the customer.
        /// Card nonces are generated by the Square Payment Form when customers enter
        /// their card information. See
        /// [Embedding the payment form](https://developer.squareup.com/docs/payment-form/payment-form-walkthrough) for
        /// more information.
        /// __NOTE:__ Card nonces generated by digital wallets (e.g., Apple Pay)
        /// cannot be used to create a customer card.
        /// </summary>
        [JsonProperty("card_nonce")]
        public string CardNonce { get; }

        /// <summary>
        /// Represents a physical address.
        /// </summary>
        [JsonProperty("billing_address")]
        public Models.Address BillingAddress { get; }

        /// <summary>
        /// The full name printed on the credit card.
        /// </summary>
        [JsonProperty("cardholder_name")]
        public string CardholderName { get; }

        /// <summary>
        /// An identifying token generated by `SqPaymentForm.verifyBuyer()`.
        /// Verification tokens encapsulate customer device information and 3-D Secure
        /// challenge results to indicate that Square has verified the buyer identity.
        /// </summary>
        [JsonProperty("verification_token")]
        public string VerificationToken { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder(CardNonce)
                .BillingAddress(BillingAddress)
                .CardholderName(CardholderName)
                .VerificationToken(VerificationToken);
            return builder;
        }

        public class Builder
        {
            private string cardNonce;
            private Models.Address billingAddress;
            private string cardholderName;
            private string verificationToken;

            public Builder(string cardNonce)
            {
                this.cardNonce = cardNonce;
            }
            public Builder CardNonce(string value)
            {
                cardNonce = value;
                return this;
            }

            public Builder BillingAddress(Models.Address value)
            {
                billingAddress = value;
                return this;
            }

            public Builder CardholderName(string value)
            {
                cardholderName = value;
                return this;
            }

            public Builder VerificationToken(string value)
            {
                verificationToken = value;
                return this;
            }

            public CreateCustomerCardRequest Build()
            {
                return new CreateCustomerCardRequest(cardNonce,
                    billingAddress,
                    cardholderName,
                    verificationToken);
            }
        }
    }
}