namespace Square.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Square;
    using Square.Utilities;

    /// <summary>
    /// Dispute.
    /// </summary>
    public class Dispute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Dispute"/> class.
        /// </summary>
        /// <param name="disputeId">dispute_id.</param>
        /// <param name="amountMoney">amount_money.</param>
        /// <param name="reason">reason.</param>
        /// <param name="state">state.</param>
        /// <param name="dueAt">due_at.</param>
        /// <param name="disputedPayment">disputed_payment.</param>
        /// <param name="evidenceIds">evidence_ids.</param>
        /// <param name="cardBrand">card_brand.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="brandDisputeId">brand_dispute_id.</param>
        /// <param name="reportedDate">reported_date.</param>
        /// <param name="version">version.</param>
        /// <param name="locationId">location_id.</param>
        public Dispute(
            string disputeId = null,
            Models.Money amountMoney = null,
            string reason = null,
            string state = null,
            string dueAt = null,
            Models.DisputedPayment disputedPayment = null,
            IList<string> evidenceIds = null,
            string cardBrand = null,
            string createdAt = null,
            string updatedAt = null,
            string brandDisputeId = null,
            string reportedDate = null,
            int? version = null,
            string locationId = null)
        {
            this.DisputeId = disputeId;
            this.AmountMoney = amountMoney;
            this.Reason = reason;
            this.State = state;
            this.DueAt = dueAt;
            this.DisputedPayment = disputedPayment;
            this.EvidenceIds = evidenceIds;
            this.CardBrand = cardBrand;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.BrandDisputeId = brandDisputeId;
            this.ReportedDate = reportedDate;
            this.Version = version;
            this.LocationId = locationId;
        }

        /// <summary>
        /// The unique ID for this `Dispute`, generated by Square.
        /// </summary>
        [JsonProperty("dispute_id", NullValueHandling = NullValueHandling.Ignore)]
        public string DisputeId { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("amount_money", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money AmountMoney { get; }

        /// <summary>
        /// The list of possible reasons why a cardholder might initiate a
        /// dispute with their bank.
        /// </summary>
        [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
        public string Reason { get; }

        /// <summary>
        /// The list of possible dispute states.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public string State { get; }

        /// <summary>
        /// The time when the next action is due, in RFC 3339 format.
        /// </summary>
        [JsonProperty("due_at", NullValueHandling = NullValueHandling.Ignore)]
        public string DueAt { get; }

        /// <summary>
        /// The payment the cardholder disputed.
        /// </summary>
        [JsonProperty("disputed_payment", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DisputedPayment DisputedPayment { get; }

        /// <summary>
        /// The IDs of the evidence associated with the dispute.
        /// </summary>
        [JsonProperty("evidence_ids", NullValueHandling = NullValueHandling.Ignore)]
        public IList<string> EvidenceIds { get; }

        /// <summary>
        /// Indicates a card's brand, such as `VISA` or `MASTERCARD`.
        /// </summary>
        [JsonProperty("card_brand", NullValueHandling = NullValueHandling.Ignore)]
        public string CardBrand { get; }

        /// <summary>
        /// The timestamp when the dispute was created, in RFC 3339 format.
        /// </summary>
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedAt { get; }

        /// <summary>
        /// The timestamp when the dispute was last updated, in RFC 3339 format.
        /// </summary>
        [JsonProperty("updated_at", NullValueHandling = NullValueHandling.Ignore)]
        public string UpdatedAt { get; }

        /// <summary>
        /// The ID of the dispute in the card brand system, generated by the card brand.
        /// </summary>
        [JsonProperty("brand_dispute_id", NullValueHandling = NullValueHandling.Ignore)]
        public string BrandDisputeId { get; }

        /// <summary>
        /// The timestamp when the dispute was reported, in RFC 3339 format.
        /// </summary>
        [JsonProperty("reported_date", NullValueHandling = NullValueHandling.Ignore)]
        public string ReportedDate { get; }

        /// <summary>
        /// The current version of the `Dispute`.
        /// </summary>
        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public int? Version { get; }

        /// <summary>
        /// The ID of the location where the dispute originated.
        /// </summary>
        [JsonProperty("location_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationId { get; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();

            this.ToString(toStringOutput);

            return $"Dispute : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (obj == this)
            {
                return true;
            }

            return obj is Dispute other &&
                ((this.DisputeId == null && other.DisputeId == null) || (this.DisputeId?.Equals(other.DisputeId) == true)) &&
                ((this.AmountMoney == null && other.AmountMoney == null) || (this.AmountMoney?.Equals(other.AmountMoney) == true)) &&
                ((this.Reason == null && other.Reason == null) || (this.Reason?.Equals(other.Reason) == true)) &&
                ((this.State == null && other.State == null) || (this.State?.Equals(other.State) == true)) &&
                ((this.DueAt == null && other.DueAt == null) || (this.DueAt?.Equals(other.DueAt) == true)) &&
                ((this.DisputedPayment == null && other.DisputedPayment == null) || (this.DisputedPayment?.Equals(other.DisputedPayment) == true)) &&
                ((this.EvidenceIds == null && other.EvidenceIds == null) || (this.EvidenceIds?.Equals(other.EvidenceIds) == true)) &&
                ((this.CardBrand == null && other.CardBrand == null) || (this.CardBrand?.Equals(other.CardBrand) == true)) &&
                ((this.CreatedAt == null && other.CreatedAt == null) || (this.CreatedAt?.Equals(other.CreatedAt) == true)) &&
                ((this.UpdatedAt == null && other.UpdatedAt == null) || (this.UpdatedAt?.Equals(other.UpdatedAt) == true)) &&
                ((this.BrandDisputeId == null && other.BrandDisputeId == null) || (this.BrandDisputeId?.Equals(other.BrandDisputeId) == true)) &&
                ((this.ReportedDate == null && other.ReportedDate == null) || (this.ReportedDate?.Equals(other.ReportedDate) == true)) &&
                ((this.Version == null && other.Version == null) || (this.Version?.Equals(other.Version) == true)) &&
                ((this.LocationId == null && other.LocationId == null) || (this.LocationId?.Equals(other.LocationId) == true));
        }

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            int hashCode = 1993475725;

            if (this.DisputeId != null)
            {
               hashCode += this.DisputeId.GetHashCode();
            }

            if (this.AmountMoney != null)
            {
               hashCode += this.AmountMoney.GetHashCode();
            }

            if (this.Reason != null)
            {
               hashCode += this.Reason.GetHashCode();
            }

            if (this.State != null)
            {
               hashCode += this.State.GetHashCode();
            }

            if (this.DueAt != null)
            {
               hashCode += this.DueAt.GetHashCode();
            }

            if (this.DisputedPayment != null)
            {
               hashCode += this.DisputedPayment.GetHashCode();
            }

            if (this.EvidenceIds != null)
            {
               hashCode += this.EvidenceIds.GetHashCode();
            }

            if (this.CardBrand != null)
            {
               hashCode += this.CardBrand.GetHashCode();
            }

            if (this.CreatedAt != null)
            {
               hashCode += this.CreatedAt.GetHashCode();
            }

            if (this.UpdatedAt != null)
            {
               hashCode += this.UpdatedAt.GetHashCode();
            }

            if (this.BrandDisputeId != null)
            {
               hashCode += this.BrandDisputeId.GetHashCode();
            }

            if (this.ReportedDate != null)
            {
               hashCode += this.ReportedDate.GetHashCode();
            }

            if (this.Version != null)
            {
               hashCode += this.Version.GetHashCode();
            }

            if (this.LocationId != null)
            {
               hashCode += this.LocationId.GetHashCode();
            }

            return hashCode;
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"this.DisputeId = {(this.DisputeId == null ? "null" : this.DisputeId == string.Empty ? "" : this.DisputeId)}");
            toStringOutput.Add($"this.AmountMoney = {(this.AmountMoney == null ? "null" : this.AmountMoney.ToString())}");
            toStringOutput.Add($"this.Reason = {(this.Reason == null ? "null" : this.Reason.ToString())}");
            toStringOutput.Add($"this.State = {(this.State == null ? "null" : this.State.ToString())}");
            toStringOutput.Add($"this.DueAt = {(this.DueAt == null ? "null" : this.DueAt == string.Empty ? "" : this.DueAt)}");
            toStringOutput.Add($"this.DisputedPayment = {(this.DisputedPayment == null ? "null" : this.DisputedPayment.ToString())}");
            toStringOutput.Add($"this.EvidenceIds = {(this.EvidenceIds == null ? "null" : $"[{string.Join(", ", this.EvidenceIds)} ]")}");
            toStringOutput.Add($"this.CardBrand = {(this.CardBrand == null ? "null" : this.CardBrand.ToString())}");
            toStringOutput.Add($"this.CreatedAt = {(this.CreatedAt == null ? "null" : this.CreatedAt == string.Empty ? "" : this.CreatedAt)}");
            toStringOutput.Add($"this.UpdatedAt = {(this.UpdatedAt == null ? "null" : this.UpdatedAt == string.Empty ? "" : this.UpdatedAt)}");
            toStringOutput.Add($"this.BrandDisputeId = {(this.BrandDisputeId == null ? "null" : this.BrandDisputeId == string.Empty ? "" : this.BrandDisputeId)}");
            toStringOutput.Add($"this.ReportedDate = {(this.ReportedDate == null ? "null" : this.ReportedDate == string.Empty ? "" : this.ReportedDate)}");
            toStringOutput.Add($"this.Version = {(this.Version == null ? "null" : this.Version.ToString())}");
            toStringOutput.Add($"this.LocationId = {(this.LocationId == null ? "null" : this.LocationId == string.Empty ? "" : this.LocationId)}");
        }

        /// <summary>
        /// Converts to builder object.
        /// </summary>
        /// <returns> Builder. </returns>
        public Builder ToBuilder()
        {
            var builder = new Builder()
                .DisputeId(this.DisputeId)
                .AmountMoney(this.AmountMoney)
                .Reason(this.Reason)
                .State(this.State)
                .DueAt(this.DueAt)
                .DisputedPayment(this.DisputedPayment)
                .EvidenceIds(this.EvidenceIds)
                .CardBrand(this.CardBrand)
                .CreatedAt(this.CreatedAt)
                .UpdatedAt(this.UpdatedAt)
                .BrandDisputeId(this.BrandDisputeId)
                .ReportedDate(this.ReportedDate)
                .Version(this.Version)
                .LocationId(this.LocationId);
            return builder;
        }

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private string disputeId;
            private Models.Money amountMoney;
            private string reason;
            private string state;
            private string dueAt;
            private Models.DisputedPayment disputedPayment;
            private IList<string> evidenceIds;
            private string cardBrand;
            private string createdAt;
            private string updatedAt;
            private string brandDisputeId;
            private string reportedDate;
            private int? version;
            private string locationId;

             /// <summary>
             /// DisputeId.
             /// </summary>
             /// <param name="disputeId"> disputeId. </param>
             /// <returns> Builder. </returns>
            public Builder DisputeId(string disputeId)
            {
                this.disputeId = disputeId;
                return this;
            }

             /// <summary>
             /// AmountMoney.
             /// </summary>
             /// <param name="amountMoney"> amountMoney. </param>
             /// <returns> Builder. </returns>
            public Builder AmountMoney(Models.Money amountMoney)
            {
                this.amountMoney = amountMoney;
                return this;
            }

             /// <summary>
             /// Reason.
             /// </summary>
             /// <param name="reason"> reason. </param>
             /// <returns> Builder. </returns>
            public Builder Reason(string reason)
            {
                this.reason = reason;
                return this;
            }

             /// <summary>
             /// State.
             /// </summary>
             /// <param name="state"> state. </param>
             /// <returns> Builder. </returns>
            public Builder State(string state)
            {
                this.state = state;
                return this;
            }

             /// <summary>
             /// DueAt.
             /// </summary>
             /// <param name="dueAt"> dueAt. </param>
             /// <returns> Builder. </returns>
            public Builder DueAt(string dueAt)
            {
                this.dueAt = dueAt;
                return this;
            }

             /// <summary>
             /// DisputedPayment.
             /// </summary>
             /// <param name="disputedPayment"> disputedPayment. </param>
             /// <returns> Builder. </returns>
            public Builder DisputedPayment(Models.DisputedPayment disputedPayment)
            {
                this.disputedPayment = disputedPayment;
                return this;
            }

             /// <summary>
             /// EvidenceIds.
             /// </summary>
             /// <param name="evidenceIds"> evidenceIds. </param>
             /// <returns> Builder. </returns>
            public Builder EvidenceIds(IList<string> evidenceIds)
            {
                this.evidenceIds = evidenceIds;
                return this;
            }

             /// <summary>
             /// CardBrand.
             /// </summary>
             /// <param name="cardBrand"> cardBrand. </param>
             /// <returns> Builder. </returns>
            public Builder CardBrand(string cardBrand)
            {
                this.cardBrand = cardBrand;
                return this;
            }

             /// <summary>
             /// CreatedAt.
             /// </summary>
             /// <param name="createdAt"> createdAt. </param>
             /// <returns> Builder. </returns>
            public Builder CreatedAt(string createdAt)
            {
                this.createdAt = createdAt;
                return this;
            }

             /// <summary>
             /// UpdatedAt.
             /// </summary>
             /// <param name="updatedAt"> updatedAt. </param>
             /// <returns> Builder. </returns>
            public Builder UpdatedAt(string updatedAt)
            {
                this.updatedAt = updatedAt;
                return this;
            }

             /// <summary>
             /// BrandDisputeId.
             /// </summary>
             /// <param name="brandDisputeId"> brandDisputeId. </param>
             /// <returns> Builder. </returns>
            public Builder BrandDisputeId(string brandDisputeId)
            {
                this.brandDisputeId = brandDisputeId;
                return this;
            }

             /// <summary>
             /// ReportedDate.
             /// </summary>
             /// <param name="reportedDate"> reportedDate. </param>
             /// <returns> Builder. </returns>
            public Builder ReportedDate(string reportedDate)
            {
                this.reportedDate = reportedDate;
                return this;
            }

             /// <summary>
             /// Version.
             /// </summary>
             /// <param name="version"> version. </param>
             /// <returns> Builder. </returns>
            public Builder Version(int? version)
            {
                this.version = version;
                return this;
            }

             /// <summary>
             /// LocationId.
             /// </summary>
             /// <param name="locationId"> locationId. </param>
             /// <returns> Builder. </returns>
            public Builder LocationId(string locationId)
            {
                this.locationId = locationId;
                return this;
            }

            /// <summary>
            /// Builds class object.
            /// </summary>
            /// <returns> Dispute. </returns>
            public Dispute Build()
            {
                return new Dispute(
                    this.disputeId,
                    this.amountMoney,
                    this.reason,
                    this.state,
                    this.dueAt,
                    this.disputedPayment,
                    this.evidenceIds,
                    this.cardBrand,
                    this.createdAt,
                    this.updatedAt,
                    this.brandDisputeId,
                    this.reportedDate,
                    this.version,
                    this.locationId);
            }
        }
    }
}