namespace Square.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Square;
    using Square.Utilities;

    /// <summary>
    /// InventoryAdjustment.
    /// </summary>
    public class InventoryAdjustment
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InventoryAdjustment"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="referenceId">reference_id.</param>
        /// <param name="fromState">from_state.</param>
        /// <param name="toState">to_state.</param>
        /// <param name="locationId">location_id.</param>
        /// <param name="catalogObjectId">catalog_object_id.</param>
        /// <param name="catalogObjectType">catalog_object_type.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="totalPriceMoney">total_price_money.</param>
        /// <param name="occurredAt">occurred_at.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="source">source.</param>
        /// <param name="employeeId">employee_id.</param>
        /// <param name="transactionId">transaction_id.</param>
        /// <param name="refundId">refund_id.</param>
        /// <param name="purchaseOrderId">purchase_order_id.</param>
        /// <param name="goodsReceiptId">goods_receipt_id.</param>
        public InventoryAdjustment(
            string id = null,
            string referenceId = null,
            string fromState = null,
            string toState = null,
            string locationId = null,
            string catalogObjectId = null,
            string catalogObjectType = null,
            string quantity = null,
            Models.Money totalPriceMoney = null,
            string occurredAt = null,
            string createdAt = null,
            Models.SourceApplication source = null,
            string employeeId = null,
            string transactionId = null,
            string refundId = null,
            string purchaseOrderId = null,
            string goodsReceiptId = null)
        {
            this.Id = id;
            this.ReferenceId = referenceId;
            this.FromState = fromState;
            this.ToState = toState;
            this.LocationId = locationId;
            this.CatalogObjectId = catalogObjectId;
            this.CatalogObjectType = catalogObjectType;
            this.Quantity = quantity;
            this.TotalPriceMoney = totalPriceMoney;
            this.OccurredAt = occurredAt;
            this.CreatedAt = createdAt;
            this.Source = source;
            this.EmployeeId = employeeId;
            this.TransactionId = transactionId;
            this.RefundId = refundId;
            this.PurchaseOrderId = purchaseOrderId;
            this.GoodsReceiptId = goodsReceiptId;
        }

        /// <summary>
        /// A unique ID generated by Square for the
        /// `InventoryAdjustment`.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; }

        /// <summary>
        /// An optional ID provided by the application to tie the
        /// `InventoryAdjustment` to an external
        /// system.
        /// </summary>
        [JsonProperty("reference_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ReferenceId { get; }

        /// <summary>
        /// Indicates the state of a tracked item quantity in the lifecycle of goods.
        /// </summary>
        [JsonProperty("from_state", NullValueHandling = NullValueHandling.Ignore)]
        public string FromState { get; }

        /// <summary>
        /// Indicates the state of a tracked item quantity in the lifecycle of goods.
        /// </summary>
        [JsonProperty("to_state", NullValueHandling = NullValueHandling.Ignore)]
        public string ToState { get; }

        /// <summary>
        /// The Square-generated ID of the [Location]($m/Location) where the related
        /// quantity of items is being tracked.
        /// </summary>
        [JsonProperty("location_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationId { get; }

        /// <summary>
        /// The Square-generated ID of the
        /// [CatalogObject]($m/CatalogObject) being tracked.
        /// </summary>
        [JsonProperty("catalog_object_id", NullValueHandling = NullValueHandling.Ignore)]
        public string CatalogObjectId { get; }

        /// <summary>
        /// The [type](entity:CatalogObjectType] of the
        /// [CatalogObject]($m/CatalogObject) being tracked. Tracking is only
        /// supported for the `ITEM_VARIATION` type.
        /// </summary>
        [JsonProperty("catalog_object_type", NullValueHandling = NullValueHandling.Ignore)]
        public string CatalogObjectType { get; }

        /// <summary>
        /// The number of items affected by the adjustment as a decimal string.
        /// Can support up to 5 digits after the decimal point.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        public string Quantity { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("total_price_money", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money TotalPriceMoney { get; }

        /// <summary>
        /// A client-generated RFC 3339-formatted timestamp that indicates when
        /// the inventory adjustment took place. For inventory adjustment updates, the `occurred_at`
        /// timestamp cannot be older than 24 hours or in the future relative to the
        /// time of the request.
        /// </summary>
        [JsonProperty("occurred_at", NullValueHandling = NullValueHandling.Ignore)]
        public string OccurredAt { get; }

        /// <summary>
        /// An RFC 3339-formatted timestamp that indicates when the inventory adjustment is received.
        /// </summary>
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedAt { get; }

        /// <summary>
        /// Provides information about the application used to generate a change.
        /// </summary>
        [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SourceApplication Source { get; }

        /// <summary>
        /// The Square-generated ID of the [Employee]($m/Employee) responsible for the
        /// inventory adjustment.
        /// </summary>
        [JsonProperty("employee_id", NullValueHandling = NullValueHandling.Ignore)]
        public string EmployeeId { get; }

        /// <summary>
        /// The Square-generated ID of the [Transaction][#type-transaction] that
        /// caused the adjustment. Only relevant for payment-related state
        /// transitions.
        /// </summary>
        [JsonProperty("transaction_id", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionId { get; }

        /// <summary>
        /// The Square-generated ID of the [Refund][#type-refund] that
        /// caused the adjustment. Only relevant for refund-related state
        /// transitions.
        /// </summary>
        [JsonProperty("refund_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RefundId { get; }

        /// <summary>
        /// The Square-generated ID of the purchase order that caused the
        /// adjustment. Only relevant for state transitions from the Square for Retail
        /// app.
        /// </summary>
        [JsonProperty("purchase_order_id", NullValueHandling = NullValueHandling.Ignore)]
        public string PurchaseOrderId { get; }

        /// <summary>
        /// The Square-generated ID of the goods receipt that caused the
        /// adjustment. Only relevant for state transitions from the Square for Retail
        /// app.
        /// </summary>
        [JsonProperty("goods_receipt_id", NullValueHandling = NullValueHandling.Ignore)]
        public string GoodsReceiptId { get; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();

            this.ToString(toStringOutput);

            return $"InventoryAdjustment : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (obj == this)
            {
                return true;
            }

            return obj is InventoryAdjustment other &&
                ((this.Id == null && other.Id == null) || (this.Id?.Equals(other.Id) == true)) &&
                ((this.ReferenceId == null && other.ReferenceId == null) || (this.ReferenceId?.Equals(other.ReferenceId) == true)) &&
                ((this.FromState == null && other.FromState == null) || (this.FromState?.Equals(other.FromState) == true)) &&
                ((this.ToState == null && other.ToState == null) || (this.ToState?.Equals(other.ToState) == true)) &&
                ((this.LocationId == null && other.LocationId == null) || (this.LocationId?.Equals(other.LocationId) == true)) &&
                ((this.CatalogObjectId == null && other.CatalogObjectId == null) || (this.CatalogObjectId?.Equals(other.CatalogObjectId) == true)) &&
                ((this.CatalogObjectType == null && other.CatalogObjectType == null) || (this.CatalogObjectType?.Equals(other.CatalogObjectType) == true)) &&
                ((this.Quantity == null && other.Quantity == null) || (this.Quantity?.Equals(other.Quantity) == true)) &&
                ((this.TotalPriceMoney == null && other.TotalPriceMoney == null) || (this.TotalPriceMoney?.Equals(other.TotalPriceMoney) == true)) &&
                ((this.OccurredAt == null && other.OccurredAt == null) || (this.OccurredAt?.Equals(other.OccurredAt) == true)) &&
                ((this.CreatedAt == null && other.CreatedAt == null) || (this.CreatedAt?.Equals(other.CreatedAt) == true)) &&
                ((this.Source == null && other.Source == null) || (this.Source?.Equals(other.Source) == true)) &&
                ((this.EmployeeId == null && other.EmployeeId == null) || (this.EmployeeId?.Equals(other.EmployeeId) == true)) &&
                ((this.TransactionId == null && other.TransactionId == null) || (this.TransactionId?.Equals(other.TransactionId) == true)) &&
                ((this.RefundId == null && other.RefundId == null) || (this.RefundId?.Equals(other.RefundId) == true)) &&
                ((this.PurchaseOrderId == null && other.PurchaseOrderId == null) || (this.PurchaseOrderId?.Equals(other.PurchaseOrderId) == true)) &&
                ((this.GoodsReceiptId == null && other.GoodsReceiptId == null) || (this.GoodsReceiptId?.Equals(other.GoodsReceiptId) == true));
        }

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            int hashCode = -855846569;

            if (this.Id != null)
            {
               hashCode += this.Id.GetHashCode();
            }

            if (this.ReferenceId != null)
            {
               hashCode += this.ReferenceId.GetHashCode();
            }

            if (this.FromState != null)
            {
               hashCode += this.FromState.GetHashCode();
            }

            if (this.ToState != null)
            {
               hashCode += this.ToState.GetHashCode();
            }

            if (this.LocationId != null)
            {
               hashCode += this.LocationId.GetHashCode();
            }

            if (this.CatalogObjectId != null)
            {
               hashCode += this.CatalogObjectId.GetHashCode();
            }

            if (this.CatalogObjectType != null)
            {
               hashCode += this.CatalogObjectType.GetHashCode();
            }

            if (this.Quantity != null)
            {
               hashCode += this.Quantity.GetHashCode();
            }

            if (this.TotalPriceMoney != null)
            {
               hashCode += this.TotalPriceMoney.GetHashCode();
            }

            if (this.OccurredAt != null)
            {
               hashCode += this.OccurredAt.GetHashCode();
            }

            if (this.CreatedAt != null)
            {
               hashCode += this.CreatedAt.GetHashCode();
            }

            if (this.Source != null)
            {
               hashCode += this.Source.GetHashCode();
            }

            if (this.EmployeeId != null)
            {
               hashCode += this.EmployeeId.GetHashCode();
            }

            if (this.TransactionId != null)
            {
               hashCode += this.TransactionId.GetHashCode();
            }

            if (this.RefundId != null)
            {
               hashCode += this.RefundId.GetHashCode();
            }

            if (this.PurchaseOrderId != null)
            {
               hashCode += this.PurchaseOrderId.GetHashCode();
            }

            if (this.GoodsReceiptId != null)
            {
               hashCode += this.GoodsReceiptId.GetHashCode();
            }

            return hashCode;
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"this.Id = {(this.Id == null ? "null" : this.Id == string.Empty ? "" : this.Id)}");
            toStringOutput.Add($"this.ReferenceId = {(this.ReferenceId == null ? "null" : this.ReferenceId == string.Empty ? "" : this.ReferenceId)}");
            toStringOutput.Add($"this.FromState = {(this.FromState == null ? "null" : this.FromState.ToString())}");
            toStringOutput.Add($"this.ToState = {(this.ToState == null ? "null" : this.ToState.ToString())}");
            toStringOutput.Add($"this.LocationId = {(this.LocationId == null ? "null" : this.LocationId == string.Empty ? "" : this.LocationId)}");
            toStringOutput.Add($"this.CatalogObjectId = {(this.CatalogObjectId == null ? "null" : this.CatalogObjectId == string.Empty ? "" : this.CatalogObjectId)}");
            toStringOutput.Add($"this.CatalogObjectType = {(this.CatalogObjectType == null ? "null" : this.CatalogObjectType == string.Empty ? "" : this.CatalogObjectType)}");
            toStringOutput.Add($"this.Quantity = {(this.Quantity == null ? "null" : this.Quantity == string.Empty ? "" : this.Quantity)}");
            toStringOutput.Add($"this.TotalPriceMoney = {(this.TotalPriceMoney == null ? "null" : this.TotalPriceMoney.ToString())}");
            toStringOutput.Add($"this.OccurredAt = {(this.OccurredAt == null ? "null" : this.OccurredAt == string.Empty ? "" : this.OccurredAt)}");
            toStringOutput.Add($"this.CreatedAt = {(this.CreatedAt == null ? "null" : this.CreatedAt == string.Empty ? "" : this.CreatedAt)}");
            toStringOutput.Add($"this.Source = {(this.Source == null ? "null" : this.Source.ToString())}");
            toStringOutput.Add($"this.EmployeeId = {(this.EmployeeId == null ? "null" : this.EmployeeId == string.Empty ? "" : this.EmployeeId)}");
            toStringOutput.Add($"this.TransactionId = {(this.TransactionId == null ? "null" : this.TransactionId == string.Empty ? "" : this.TransactionId)}");
            toStringOutput.Add($"this.RefundId = {(this.RefundId == null ? "null" : this.RefundId == string.Empty ? "" : this.RefundId)}");
            toStringOutput.Add($"this.PurchaseOrderId = {(this.PurchaseOrderId == null ? "null" : this.PurchaseOrderId == string.Empty ? "" : this.PurchaseOrderId)}");
            toStringOutput.Add($"this.GoodsReceiptId = {(this.GoodsReceiptId == null ? "null" : this.GoodsReceiptId == string.Empty ? "" : this.GoodsReceiptId)}");
        }

        /// <summary>
        /// Converts to builder object.
        /// </summary>
        /// <returns> Builder. </returns>
        public Builder ToBuilder()
        {
            var builder = new Builder()
                .Id(this.Id)
                .ReferenceId(this.ReferenceId)
                .FromState(this.FromState)
                .ToState(this.ToState)
                .LocationId(this.LocationId)
                .CatalogObjectId(this.CatalogObjectId)
                .CatalogObjectType(this.CatalogObjectType)
                .Quantity(this.Quantity)
                .TotalPriceMoney(this.TotalPriceMoney)
                .OccurredAt(this.OccurredAt)
                .CreatedAt(this.CreatedAt)
                .Source(this.Source)
                .EmployeeId(this.EmployeeId)
                .TransactionId(this.TransactionId)
                .RefundId(this.RefundId)
                .PurchaseOrderId(this.PurchaseOrderId)
                .GoodsReceiptId(this.GoodsReceiptId);
            return builder;
        }

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private string id;
            private string referenceId;
            private string fromState;
            private string toState;
            private string locationId;
            private string catalogObjectId;
            private string catalogObjectType;
            private string quantity;
            private Models.Money totalPriceMoney;
            private string occurredAt;
            private string createdAt;
            private Models.SourceApplication source;
            private string employeeId;
            private string transactionId;
            private string refundId;
            private string purchaseOrderId;
            private string goodsReceiptId;

             /// <summary>
             /// Id.
             /// </summary>
             /// <param name="id"> id. </param>
             /// <returns> Builder. </returns>
            public Builder Id(string id)
            {
                this.id = id;
                return this;
            }

             /// <summary>
             /// ReferenceId.
             /// </summary>
             /// <param name="referenceId"> referenceId. </param>
             /// <returns> Builder. </returns>
            public Builder ReferenceId(string referenceId)
            {
                this.referenceId = referenceId;
                return this;
            }

             /// <summary>
             /// FromState.
             /// </summary>
             /// <param name="fromState"> fromState. </param>
             /// <returns> Builder. </returns>
            public Builder FromState(string fromState)
            {
                this.fromState = fromState;
                return this;
            }

             /// <summary>
             /// ToState.
             /// </summary>
             /// <param name="toState"> toState. </param>
             /// <returns> Builder. </returns>
            public Builder ToState(string toState)
            {
                this.toState = toState;
                return this;
            }

             /// <summary>
             /// LocationId.
             /// </summary>
             /// <param name="locationId"> locationId. </param>
             /// <returns> Builder. </returns>
            public Builder LocationId(string locationId)
            {
                this.locationId = locationId;
                return this;
            }

             /// <summary>
             /// CatalogObjectId.
             /// </summary>
             /// <param name="catalogObjectId"> catalogObjectId. </param>
             /// <returns> Builder. </returns>
            public Builder CatalogObjectId(string catalogObjectId)
            {
                this.catalogObjectId = catalogObjectId;
                return this;
            }

             /// <summary>
             /// CatalogObjectType.
             /// </summary>
             /// <param name="catalogObjectType"> catalogObjectType. </param>
             /// <returns> Builder. </returns>
            public Builder CatalogObjectType(string catalogObjectType)
            {
                this.catalogObjectType = catalogObjectType;
                return this;
            }

             /// <summary>
             /// Quantity.
             /// </summary>
             /// <param name="quantity"> quantity. </param>
             /// <returns> Builder. </returns>
            public Builder Quantity(string quantity)
            {
                this.quantity = quantity;
                return this;
            }

             /// <summary>
             /// TotalPriceMoney.
             /// </summary>
             /// <param name="totalPriceMoney"> totalPriceMoney. </param>
             /// <returns> Builder. </returns>
            public Builder TotalPriceMoney(Models.Money totalPriceMoney)
            {
                this.totalPriceMoney = totalPriceMoney;
                return this;
            }

             /// <summary>
             /// OccurredAt.
             /// </summary>
             /// <param name="occurredAt"> occurredAt. </param>
             /// <returns> Builder. </returns>
            public Builder OccurredAt(string occurredAt)
            {
                this.occurredAt = occurredAt;
                return this;
            }

             /// <summary>
             /// CreatedAt.
             /// </summary>
             /// <param name="createdAt"> createdAt. </param>
             /// <returns> Builder. </returns>
            public Builder CreatedAt(string createdAt)
            {
                this.createdAt = createdAt;
                return this;
            }

             /// <summary>
             /// Source.
             /// </summary>
             /// <param name="source"> source. </param>
             /// <returns> Builder. </returns>
            public Builder Source(Models.SourceApplication source)
            {
                this.source = source;
                return this;
            }

             /// <summary>
             /// EmployeeId.
             /// </summary>
             /// <param name="employeeId"> employeeId. </param>
             /// <returns> Builder. </returns>
            public Builder EmployeeId(string employeeId)
            {
                this.employeeId = employeeId;
                return this;
            }

             /// <summary>
             /// TransactionId.
             /// </summary>
             /// <param name="transactionId"> transactionId. </param>
             /// <returns> Builder. </returns>
            public Builder TransactionId(string transactionId)
            {
                this.transactionId = transactionId;
                return this;
            }

             /// <summary>
             /// RefundId.
             /// </summary>
             /// <param name="refundId"> refundId. </param>
             /// <returns> Builder. </returns>
            public Builder RefundId(string refundId)
            {
                this.refundId = refundId;
                return this;
            }

             /// <summary>
             /// PurchaseOrderId.
             /// </summary>
             /// <param name="purchaseOrderId"> purchaseOrderId. </param>
             /// <returns> Builder. </returns>
            public Builder PurchaseOrderId(string purchaseOrderId)
            {
                this.purchaseOrderId = purchaseOrderId;
                return this;
            }

             /// <summary>
             /// GoodsReceiptId.
             /// </summary>
             /// <param name="goodsReceiptId"> goodsReceiptId. </param>
             /// <returns> Builder. </returns>
            public Builder GoodsReceiptId(string goodsReceiptId)
            {
                this.goodsReceiptId = goodsReceiptId;
                return this;
            }

            /// <summary>
            /// Builds class object.
            /// </summary>
            /// <returns> InventoryAdjustment. </returns>
            public InventoryAdjustment Build()
            {
                return new InventoryAdjustment(
                    this.id,
                    this.referenceId,
                    this.fromState,
                    this.toState,
                    this.locationId,
                    this.catalogObjectId,
                    this.catalogObjectType,
                    this.quantity,
                    this.totalPriceMoney,
                    this.occurredAt,
                    this.createdAt,
                    this.source,
                    this.employeeId,
                    this.transactionId,
                    this.refundId,
                    this.purchaseOrderId,
                    this.goodsReceiptId);
            }
        }
    }
}