using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class ListMerchantsRequest 
    {
        public ListMerchantsRequest(int? cursor = null)
        {
            Cursor = cursor;
        }

        /// <summary>
        /// The cursor generated by the previous response.
        /// </summary>
        [JsonProperty("cursor")]
        public int? Cursor { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder()
                .Cursor(Cursor);
            return builder;
        }

        public class Builder
        {
            private int? cursor;

            public Builder() { }
            public Builder Cursor(int? value)
            {
                cursor = value;
                return this;
            }

            public ListMerchantsRequest Build()
            {
                return new ListMerchantsRequest(cursor);
            }
        }
    }
}