
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class LoyaltyEvent 
    {
        public LoyaltyEvent(string id,
            string type,
            string createdAt,
            string loyaltyAccountId,
            string source,
            Models.LoyaltyEventAccumulatePoints accumulatePoints = null,
            Models.LoyaltyEventCreateReward createReward = null,
            Models.LoyaltyEventRedeemReward redeemReward = null,
            Models.LoyaltyEventDeleteReward deleteReward = null,
            Models.LoyaltyEventAdjustPoints adjustPoints = null,
            string locationId = null,
            Models.LoyaltyEventExpirePoints expirePoints = null,
            Models.LoyaltyEventOther otherEvent = null)
        {
            Id = id;
            Type = type;
            CreatedAt = createdAt;
            AccumulatePoints = accumulatePoints;
            CreateReward = createReward;
            RedeemReward = redeemReward;
            DeleteReward = deleteReward;
            AdjustPoints = adjustPoints;
            LoyaltyAccountId = loyaltyAccountId;
            LocationId = locationId;
            Source = source;
            ExpirePoints = expirePoints;
            OtherEvent = otherEvent;
        }

        /// <summary>
        /// The Square-assigned ID of the loyalty event.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; }

        /// <summary>
        /// The type of the loyalty event.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; }

        /// <summary>
        /// The timestamp when the event was created, in RFC 3339 format.
        /// </summary>
        [JsonProperty("created_at")]
        public string CreatedAt { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `ACCUMULATE_POINTS`.
        /// </summary>
        [JsonProperty("accumulate_points", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventAccumulatePoints AccumulatePoints { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `CREATE_REWARD`.
        /// </summary>
        [JsonProperty("create_reward", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventCreateReward CreateReward { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `REDEEM_REWARD`.
        /// </summary>
        [JsonProperty("redeem_reward", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventRedeemReward RedeemReward { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `DELETE_REWARD`.
        /// </summary>
        [JsonProperty("delete_reward", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventDeleteReward DeleteReward { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `ADJUST_POINTS`.
        /// </summary>
        [JsonProperty("adjust_points", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventAdjustPoints AdjustPoints { get; }

        /// <summary>
        /// The ID of the [loyalty account](#type-LoyaltyAccount) in which the event occurred.
        /// </summary>
        [JsonProperty("loyalty_account_id")]
        public string LoyaltyAccountId { get; }

        /// <summary>
        /// The ID of the [location](#type-Location) where the event occurred.
        /// </summary>
        [JsonProperty("location_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationId { get; }

        /// <summary>
        /// Defines whether the event was generated by the Square Point of Sale.
        /// </summary>
        [JsonProperty("source")]
        public string Source { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `EXPIRE_POINTS`.
        /// </summary>
        [JsonProperty("expire_points", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventExpirePoints ExpirePoints { get; }

        /// <summary>
        /// Provides metadata when the event `type` is `OTHER`.
        /// </summary>
        [JsonProperty("other_event", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LoyaltyEventOther OtherEvent { get; }

        public override string ToString()
        {
            var toStringOutput = new List<string>();

            this.ToString(toStringOutput);

            return $"LoyaltyEvent : ({string.Join(", ", toStringOutput)})";
        }

        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(Id == null ? "null" : Id == string.Empty ? "" : Id)}");
            toStringOutput.Add($"Type = {(Type == null ? "null" : Type.ToString())}");
            toStringOutput.Add($"CreatedAt = {(CreatedAt == null ? "null" : CreatedAt == string.Empty ? "" : CreatedAt)}");
            toStringOutput.Add($"AccumulatePoints = {(AccumulatePoints == null ? "null" : AccumulatePoints.ToString())}");
            toStringOutput.Add($"CreateReward = {(CreateReward == null ? "null" : CreateReward.ToString())}");
            toStringOutput.Add($"RedeemReward = {(RedeemReward == null ? "null" : RedeemReward.ToString())}");
            toStringOutput.Add($"DeleteReward = {(DeleteReward == null ? "null" : DeleteReward.ToString())}");
            toStringOutput.Add($"AdjustPoints = {(AdjustPoints == null ? "null" : AdjustPoints.ToString())}");
            toStringOutput.Add($"LoyaltyAccountId = {(LoyaltyAccountId == null ? "null" : LoyaltyAccountId == string.Empty ? "" : LoyaltyAccountId)}");
            toStringOutput.Add($"LocationId = {(LocationId == null ? "null" : LocationId == string.Empty ? "" : LocationId)}");
            toStringOutput.Add($"Source = {(Source == null ? "null" : Source.ToString())}");
            toStringOutput.Add($"ExpirePoints = {(ExpirePoints == null ? "null" : ExpirePoints.ToString())}");
            toStringOutput.Add($"OtherEvent = {(OtherEvent == null ? "null" : OtherEvent.ToString())}");
        }

        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (obj == this)
            {
                return true;
            }

            return obj is LoyaltyEvent other &&
                ((Id == null && other.Id == null) || (Id?.Equals(other.Id) == true)) &&
                ((Type == null && other.Type == null) || (Type?.Equals(other.Type) == true)) &&
                ((CreatedAt == null && other.CreatedAt == null) || (CreatedAt?.Equals(other.CreatedAt) == true)) &&
                ((AccumulatePoints == null && other.AccumulatePoints == null) || (AccumulatePoints?.Equals(other.AccumulatePoints) == true)) &&
                ((CreateReward == null && other.CreateReward == null) || (CreateReward?.Equals(other.CreateReward) == true)) &&
                ((RedeemReward == null && other.RedeemReward == null) || (RedeemReward?.Equals(other.RedeemReward) == true)) &&
                ((DeleteReward == null && other.DeleteReward == null) || (DeleteReward?.Equals(other.DeleteReward) == true)) &&
                ((AdjustPoints == null && other.AdjustPoints == null) || (AdjustPoints?.Equals(other.AdjustPoints) == true)) &&
                ((LoyaltyAccountId == null && other.LoyaltyAccountId == null) || (LoyaltyAccountId?.Equals(other.LoyaltyAccountId) == true)) &&
                ((LocationId == null && other.LocationId == null) || (LocationId?.Equals(other.LocationId) == true)) &&
                ((Source == null && other.Source == null) || (Source?.Equals(other.Source) == true)) &&
                ((ExpirePoints == null && other.ExpirePoints == null) || (ExpirePoints?.Equals(other.ExpirePoints) == true)) &&
                ((OtherEvent == null && other.OtherEvent == null) || (OtherEvent?.Equals(other.OtherEvent) == true));
        }

        public override int GetHashCode()
        {
            int hashCode = 1490090338;

            if (Id != null)
            {
               hashCode += Id.GetHashCode();
            }

            if (Type != null)
            {
               hashCode += Type.GetHashCode();
            }

            if (CreatedAt != null)
            {
               hashCode += CreatedAt.GetHashCode();
            }

            if (AccumulatePoints != null)
            {
               hashCode += AccumulatePoints.GetHashCode();
            }

            if (CreateReward != null)
            {
               hashCode += CreateReward.GetHashCode();
            }

            if (RedeemReward != null)
            {
               hashCode += RedeemReward.GetHashCode();
            }

            if (DeleteReward != null)
            {
               hashCode += DeleteReward.GetHashCode();
            }

            if (AdjustPoints != null)
            {
               hashCode += AdjustPoints.GetHashCode();
            }

            if (LoyaltyAccountId != null)
            {
               hashCode += LoyaltyAccountId.GetHashCode();
            }

            if (LocationId != null)
            {
               hashCode += LocationId.GetHashCode();
            }

            if (Source != null)
            {
               hashCode += Source.GetHashCode();
            }

            if (ExpirePoints != null)
            {
               hashCode += ExpirePoints.GetHashCode();
            }

            if (OtherEvent != null)
            {
               hashCode += OtherEvent.GetHashCode();
            }

            return hashCode;
        }

        public Builder ToBuilder()
        {
            var builder = new Builder(Id,
                Type,
                CreatedAt,
                LoyaltyAccountId,
                Source)
                .AccumulatePoints(AccumulatePoints)
                .CreateReward(CreateReward)
                .RedeemReward(RedeemReward)
                .DeleteReward(DeleteReward)
                .AdjustPoints(AdjustPoints)
                .LocationId(LocationId)
                .ExpirePoints(ExpirePoints)
                .OtherEvent(OtherEvent);
            return builder;
        }

        public class Builder
        {
            private string id;
            private string type;
            private string createdAt;
            private string loyaltyAccountId;
            private string source;
            private Models.LoyaltyEventAccumulatePoints accumulatePoints;
            private Models.LoyaltyEventCreateReward createReward;
            private Models.LoyaltyEventRedeemReward redeemReward;
            private Models.LoyaltyEventDeleteReward deleteReward;
            private Models.LoyaltyEventAdjustPoints adjustPoints;
            private string locationId;
            private Models.LoyaltyEventExpirePoints expirePoints;
            private Models.LoyaltyEventOther otherEvent;

            public Builder(string id,
                string type,
                string createdAt,
                string loyaltyAccountId,
                string source)
            {
                this.id = id;
                this.type = type;
                this.createdAt = createdAt;
                this.loyaltyAccountId = loyaltyAccountId;
                this.source = source;
            }

            public Builder Id(string id)
            {
                this.id = id;
                return this;
            }

            public Builder Type(string type)
            {
                this.type = type;
                return this;
            }

            public Builder CreatedAt(string createdAt)
            {
                this.createdAt = createdAt;
                return this;
            }

            public Builder LoyaltyAccountId(string loyaltyAccountId)
            {
                this.loyaltyAccountId = loyaltyAccountId;
                return this;
            }

            public Builder Source(string source)
            {
                this.source = source;
                return this;
            }

            public Builder AccumulatePoints(Models.LoyaltyEventAccumulatePoints accumulatePoints)
            {
                this.accumulatePoints = accumulatePoints;
                return this;
            }

            public Builder CreateReward(Models.LoyaltyEventCreateReward createReward)
            {
                this.createReward = createReward;
                return this;
            }

            public Builder RedeemReward(Models.LoyaltyEventRedeemReward redeemReward)
            {
                this.redeemReward = redeemReward;
                return this;
            }

            public Builder DeleteReward(Models.LoyaltyEventDeleteReward deleteReward)
            {
                this.deleteReward = deleteReward;
                return this;
            }

            public Builder AdjustPoints(Models.LoyaltyEventAdjustPoints adjustPoints)
            {
                this.adjustPoints = adjustPoints;
                return this;
            }

            public Builder LocationId(string locationId)
            {
                this.locationId = locationId;
                return this;
            }

            public Builder ExpirePoints(Models.LoyaltyEventExpirePoints expirePoints)
            {
                this.expirePoints = expirePoints;
                return this;
            }

            public Builder OtherEvent(Models.LoyaltyEventOther otherEvent)
            {
                this.otherEvent = otherEvent;
                return this;
            }

            public LoyaltyEvent Build()
            {
                return new LoyaltyEvent(id,
                    type,
                    createdAt,
                    loyaltyAccountId,
                    source,
                    accumulatePoints,
                    createReward,
                    redeemReward,
                    deleteReward,
                    adjustPoints,
                    locationId,
                    expirePoints,
                    otherEvent);
            }
        }
    }
}