using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class OrderFulfillment 
    {
        public OrderFulfillment(string uid = null,
            string type = null,
            string state = null,
            IDictionary<string, string> metadata = null,
            Models.OrderFulfillmentPickupDetails pickupDetails = null,
            Models.OrderFulfillmentShipmentDetails shipmentDetails = null)
        {
            Uid = uid;
            Type = type;
            State = state;
            Metadata = metadata;
            PickupDetails = pickupDetails;
            ShipmentDetails = shipmentDetails;
        }

        /// <summary>
        /// Unique ID that identifies the fulfillment only within this order.
        /// </summary>
        [JsonProperty("uid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uid { get; }

        /// <summary>
        /// The type of fulfillment.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; }

        /// <summary>
        /// The current state of this fulfillment.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public string State { get; }

        /// <summary>
        /// Application-defined data attached to this fulfillment. Metadata fields are intended
        /// to store descriptive references or associations with an entity in another system or store brief
        /// information about the object. Square does not process this field; it only stores and returns it
        /// in relevant API calls. Do not use metadata to store any sensitive information (personally
        /// identifiable information, card details, etc.).
        /// Keys written by applications must be 60 characters or less and must be in the character set
        /// `[a-zA-Z0-9_-]`. Entries may also include metadata generated by Square. These keys are prefixed
        /// with a namespace, separated from the key with a ':' character.
        /// Values have a max length of 255 characters.
        /// An application may have up to 10 entries per metadata field.
        /// Entries written by applications are private and can only be read or modified by the same
        /// application.
        /// See [Metadata](https://developer.squareup.com/docs/build-basics/metadata) for more information.
        /// </summary>
        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
        public IDictionary<string, string> Metadata { get; }

        /// <summary>
        /// Contains details necessary to fulfill a pickup order.
        /// </summary>
        [JsonProperty("pickup_details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.OrderFulfillmentPickupDetails PickupDetails { get; }

        /// <summary>
        /// Contains details necessary to fulfill a shipment order.
        /// </summary>
        [JsonProperty("shipment_details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.OrderFulfillmentShipmentDetails ShipmentDetails { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder()
                .Uid(Uid)
                .Type(Type)
                .State(State)
                .Metadata(Metadata)
                .PickupDetails(PickupDetails)
                .ShipmentDetails(ShipmentDetails);
            return builder;
        }

        public class Builder
        {
            private string uid;
            private string type;
            private string state;
            private IDictionary<string, string> metadata;
            private Models.OrderFulfillmentPickupDetails pickupDetails;
            private Models.OrderFulfillmentShipmentDetails shipmentDetails;



            public Builder Uid(string uid)
            {
                this.uid = uid;
                return this;
            }

            public Builder Type(string type)
            {
                this.type = type;
                return this;
            }

            public Builder State(string state)
            {
                this.state = state;
                return this;
            }

            public Builder Metadata(IDictionary<string, string> metadata)
            {
                this.metadata = metadata;
                return this;
            }

            public Builder PickupDetails(Models.OrderFulfillmentPickupDetails pickupDetails)
            {
                this.pickupDetails = pickupDetails;
                return this;
            }

            public Builder ShipmentDetails(Models.OrderFulfillmentShipmentDetails shipmentDetails)
            {
                this.shipmentDetails = shipmentDetails;
                return this;
            }

            public OrderFulfillment Build()
            {
                return new OrderFulfillment(uid,
                    type,
                    state,
                    metadata,
                    pickupDetails,
                    shipmentDetails);
            }
        }
    }
}