using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class PaymentRefund 
    {
        public PaymentRefund(string id,
            Models.Money amountMoney,
            string status = null,
            string locationId = null,
            Models.Money appFeeMoney = null,
            IList<Models.ProcessingFee> processingFee = null,
            string paymentId = null,
            string orderId = null,
            string reason = null,
            string createdAt = null,
            string updatedAt = null)
        {
            Id = id;
            Status = status;
            LocationId = locationId;
            AmountMoney = amountMoney;
            AppFeeMoney = appFeeMoney;
            ProcessingFee = processingFee;
            PaymentId = paymentId;
            OrderId = orderId;
            Reason = reason;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Unique ID for this refund, generated by Square.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; }

        /// <summary>
        /// The refund's status:
        /// - `PENDING` - awaiting approval
        /// - `COMPLETED` - successfully completed
        /// - `REJECTED` - the refund was rejected
        /// - `FAILED` - an error occurred
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; }

        /// <summary>
        /// Location ID associated with the payment this refund is attached to.
        /// </summary>
        [JsonProperty("location_id")]
        public string LocationId { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("amount_money")]
        public Models.Money AmountMoney { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("app_fee_money")]
        public Models.Money AppFeeMoney { get; }

        /// <summary>
        /// Processing fees and fee adjustments assessed by Square on this refund.
        /// </summary>
        [JsonProperty("processing_fee")]
        public IList<Models.ProcessingFee> ProcessingFee { get; }

        /// <summary>
        /// The ID of the payment assocated with this refund.
        /// </summary>
        [JsonProperty("payment_id")]
        public string PaymentId { get; }

        /// <summary>
        /// The ID of the order associated with the refund.
        /// </summary>
        [JsonProperty("order_id")]
        public string OrderId { get; }

        /// <summary>
        /// The reason for the refund.
        /// </summary>
        [JsonProperty("reason")]
        public string Reason { get; }

        /// <summary>
        /// Timestamp of when the refund was created, in RFC 3339 format.
        /// </summary>
        [JsonProperty("created_at")]
        public string CreatedAt { get; }

        /// <summary>
        /// Timestamp of when the refund was last updated, in RFC 3339 format.
        /// </summary>
        [JsonProperty("updated_at")]
        public string UpdatedAt { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder(Id,
                AmountMoney)
                .Status(Status)
                .LocationId(LocationId)
                .AppFeeMoney(AppFeeMoney)
                .ProcessingFee(ProcessingFee)
                .PaymentId(PaymentId)
                .OrderId(OrderId)
                .Reason(Reason)
                .CreatedAt(CreatedAt)
                .UpdatedAt(UpdatedAt);
            return builder;
        }

        public class Builder
        {
            private string id;
            private Models.Money amountMoney;
            private string status;
            private string locationId;
            private Models.Money appFeeMoney;
            private IList<Models.ProcessingFee> processingFee = new List<Models.ProcessingFee>();
            private string paymentId;
            private string orderId;
            private string reason;
            private string createdAt;
            private string updatedAt;

            public Builder(string id,
                Models.Money amountMoney)
            {
                this.id = id;
                this.amountMoney = amountMoney;
            }
            public Builder Id(string value)
            {
                id = value;
                return this;
            }

            public Builder AmountMoney(Models.Money value)
            {
                amountMoney = value;
                return this;
            }

            public Builder Status(string value)
            {
                status = value;
                return this;
            }

            public Builder LocationId(string value)
            {
                locationId = value;
                return this;
            }

            public Builder AppFeeMoney(Models.Money value)
            {
                appFeeMoney = value;
                return this;
            }

            public Builder ProcessingFee(IList<Models.ProcessingFee> value)
            {
                processingFee = value;
                return this;
            }

            public Builder PaymentId(string value)
            {
                paymentId = value;
                return this;
            }

            public Builder OrderId(string value)
            {
                orderId = value;
                return this;
            }

            public Builder Reason(string value)
            {
                reason = value;
                return this;
            }

            public Builder CreatedAt(string value)
            {
                createdAt = value;
                return this;
            }

            public Builder UpdatedAt(string value)
            {
                updatedAt = value;
                return this;
            }

            public PaymentRefund Build()
            {
                return new PaymentRefund(id,
                    amountMoney,
                    status,
                    locationId,
                    appFeeMoney,
                    processingFee,
                    paymentId,
                    orderId,
                    reason,
                    createdAt,
                    updatedAt);
            }
        }
    }
}