using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Square;
using Square.Utilities;

namespace Square.Models
{
    public class TenderCardDetails 
    {
        public TenderCardDetails(string status = null,
            Models.Card card = null,
            string entryMethod = null)
        {
            Status = status;
            Card = card;
            EntryMethod = entryMethod;
        }

        /// <summary>
        /// Indicates the card transaction's current status.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; }

        /// <summary>
        /// Represents the payment details of a card to be used for payments. These
        /// details are determined by the `card_nonce` generated by `SqPaymentForm`.
        /// </summary>
        [JsonProperty("card")]
        public Models.Card Card { get; }

        /// <summary>
        /// Indicates the method used to enter the card's details.
        /// </summary>
        [JsonProperty("entry_method")]
        public string EntryMethod { get; }

        public Builder ToBuilder()
        {
            var builder = new Builder()
                .Status(Status)
                .Card(Card)
                .EntryMethod(EntryMethod);
            return builder;
        }

        public class Builder
        {
            private string status;
            private Models.Card card;
            private string entryMethod;

            public Builder() { }
            public Builder Status(string value)
            {
                status = value;
                return this;
            }

            public Builder Card(Models.Card value)
            {
                card = value;
                return this;
            }

            public Builder EntryMethod(string value)
            {
                entryMethod = value;
                return this;
            }

            public TenderCardDetails Build()
            {
                return new TenderCardDetails(status,
                    card,
                    entryMethod);
            }
        }
    }
}