using System.Text.Json;
using System.Text.Json.Serialization;
using Square.Core;

namespace Square;

/// <summary>
/// Describes save-card action fields.
/// </summary>
public record SaveCardOptions
{
    /// <summary>
    /// The square-assigned ID of the customer linked to the saved card.
    /// </summary>
    [JsonPropertyName("customer_id")]
    public required string CustomerId { get; set; }

    /// <summary>
    /// The id of the created card-on-file.
    /// </summary>
    [JsonAccess(JsonAccessType.ReadOnly)]
    [JsonPropertyName("card_id")]
    public string? CardId { get; set; }

    /// <summary>
    /// An optional user-defined reference ID that can be used to associate
    /// this `Card` to another entity in an external system. For example, a customer
    /// ID generated by a third-party system.
    /// </summary>
    [JsonPropertyName("reference_id")]
    public string? ReferenceId { get; set; }

    /// <summary>
    /// Additional properties received from the response, if any.
    /// </summary>
    [JsonExtensionData]
    public IDictionary<string, JsonElement> AdditionalProperties { get; internal set; } =
        new Dictionary<string, JsonElement>();

    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
