using System.Text.Json;
using System.Text.Json.Serialization;
using Square.Core;

namespace Square;

/// <summary>
/// Represents a transaction processed with Square, either with the
/// Connect API or with Square Point of Sale.
///
/// The `tenders` field of this object lists all methods of payment used to pay in
/// the transaction.
/// </summary>
public record Transaction
{
    /// <summary>
    /// The transaction's unique ID, issued by Square payments servers.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    /// The ID of the transaction's associated location.
    /// </summary>
    [JsonPropertyName("location_id")]
    public string? LocationId { get; set; }

    /// <summary>
    /// The timestamp for when the transaction was created, in RFC 3339 format.
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    /// <summary>
    /// The tenders used to pay in the transaction.
    /// </summary>
    [JsonPropertyName("tenders")]
    public IEnumerable<Tender>? Tenders { get; set; }

    /// <summary>
    /// Refunds that have been applied to any tender in the transaction.
    /// </summary>
    [JsonPropertyName("refunds")]
    public IEnumerable<Refund>? Refunds { get; set; }

    /// <summary>
    /// If the transaction was created with the [Charge](api-endpoint:Transactions-Charge)
    /// endpoint, this value is the same as the value provided for the `reference_id`
    /// parameter in the request to that endpoint. Otherwise, it is not set.
    /// </summary>
    [JsonPropertyName("reference_id")]
    public string? ReferenceId { get; set; }

    /// <summary>
    /// The Square product that processed the transaction.
    /// See [TransactionProduct](#type-transactionproduct) for possible values
    /// </summary>
    [JsonPropertyName("product")]
    public TransactionProduct? Product { get; set; }

    /// <summary>
    /// If the transaction was created in the Square Point of Sale app, this value
    /// is the ID generated for the transaction by Square Point of Sale.
    ///
    /// This ID has no relationship to the transaction's canonical `id`, which is
    /// generated by Square's backend servers. This value is generated for bookkeeping
    /// purposes, in case the transaction cannot immediately be completed (for example,
    /// if the transaction is processed in offline mode).
    ///
    /// It is not currently possible with the Connect API to perform a transaction
    /// lookup by this value.
    /// </summary>
    [JsonPropertyName("client_id")]
    public string? ClientId { get; set; }

    /// <summary>
    /// The shipping address provided in the request, if any.
    /// </summary>
    [JsonPropertyName("shipping_address")]
    public Address? ShippingAddress { get; set; }

    /// <summary>
    /// The order_id is an identifier for the order associated with this transaction, if any.
    /// </summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; set; }

    /// <summary>
    /// Additional properties received from the response, if any.
    /// </summary>
    [JsonExtensionData]
    public IDictionary<string, JsonElement> AdditionalProperties { get; internal set; } =
        new Dictionary<string, JsonElement>();

    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
