using System.Text.Json.Serialization;
using Square.Core;

namespace Square.GiftCards;

public record GetGiftCardFromNonceRequest
{
    /// <summary>
    /// The payment token of the gift card to retrieve. Payment tokens are generated by the
    /// Web Payments SDK or In-App Payments SDK.
    /// </summary>
    [JsonPropertyName("nonce")]
    public required string Nonce { get; set; }

    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
