using System.Text.Json.Serialization;
using Square.Core;
using Square.Default;

namespace Square.Default.Customers;

[Serializable]
public record CreateCustomerCardRequest
{
    /// <summary>
    /// The Square ID of the customer profile the card is linked to.
    /// </summary>
    [JsonIgnore]
    public required string CustomerId { get; set; }

    /// <summary>
    /// A card nonce representing the credit card to link to the customer.
    ///
    /// Card nonces are generated by the Square payment form when customers enter
    /// their card information. For more information, see
    /// [Walkthrough: Integrate Square Payments in a Website](https://developer.squareup.com/docs/web-payments/take-card-payment).
    ///
    /// __NOTE:__ Card nonces generated by digital wallets (such as Apple Pay)
    /// cannot be used to create a customer card.
    /// </summary>
    [JsonPropertyName("card_nonce")]
    public required string CardNonce { get; set; }

    /// <summary>
    /// Address information for the card on file.
    ///
    /// __NOTE:__ If a billing address is provided in the request, the
    /// `CreateCustomerCardRequest.billing_address.postal_code` must match
    /// the postal code encoded in the card nonce.
    /// </summary>
    [JsonPropertyName("billing_address")]
    public Address? BillingAddress { get; set; }

    /// <summary>
    /// The full name printed on the credit card.
    /// </summary>
    [JsonPropertyName("cardholder_name")]
    public string? CardholderName { get; set; }

    /// <summary>
    /// An identifying token generated by [Payments.verifyBuyer()](https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer).
    /// Verification tokens encapsulate customer device information and 3-D Secure
    /// challenge results to indicate that Square has verified the buyer identity.
    /// </summary>
    [JsonPropertyName("verification_token")]
    public string? VerificationToken { get; set; }

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
