name: CI

on:
  push:
    paths-ignore:
      - 'legacy/**'
    branches:
      - '**'
    tags:
      - '*'
      - '!*Legacy*'    # Exclude tags containing "Legacy"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - 'legacy/**'

env:
  CI: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  MSBUILDTERMINALLOGGER: off

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src/Square.sln

      - name: Build release
        id: build
        run: dotnet build src/Square.sln -c Release /p:ContinuousIntegrationBuild=true

      - name: Run Tests
        run: dotnet test src/Square.sln --no-restore  /p:ContinuousIntegrationBuild=true
        continue-on-error: true
        env:
          TEST_SQUARE_TOKEN: ${{ secrets.TEST_SQUARE_TOKEN }}

      - name: Publish to nuget.org
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && steps.build.outcome == 'success'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet pack src/Square.sln --no-build --no-restore -c Release -o dist
          dotnet nuget push dist/*.nupkg --api-key $NUGET_API_KEY --source "nuget.org"